import type { ConsultNote, Honeymoon, PrepItem } from './types';

// Readdy 프론트 목업(2026-07-22 검토)에 나온 값을 그대로 반영한 초기 목데이터.
export const weddingDate = '2027-04-12';

export const mockPrepItems: PrepItem[] = [
  {
    id: 'prep-1',
    title: '웨딩홀 3곳 견적 비교',
    category: '웨딩홀',
    assigneeName: null,
    checklist: { done: true, dueDate: '2026-08-05' },
    schedule: { scheduledAt: '2026-08-05T14:00:00+09:00', location: '논현 W웨딩홀', eventType: '상담' },
    budget: {
      plannedAmount: 18000000,
      deposit: { amount: 3000000, method: '카드', memo: '현대카드' },
      interim: { amount: 6000000, method: '현금', memo: '계좌이체' },
      balance: { amount: 9000000, method: '현금', memo: '계좌이체' },
      usedAmount: 17500000,
    },
    consultNoteIds: ['consult-1'],
  },
  {
    id: 'prep-2',
    title: '스튜디오 촬영 컨셉 확정',
    category: '스드메',
    assigneeName: '지영',
    checklist: { done: true, dueDate: '2026-08-12' },
    schedule: { scheduledAt: '2026-08-12T11:00:00+09:00', location: '청담 스튜디오B', eventType: '계약' },
    budget: {
      plannedAmount: 4500000,
      deposit: { amount: 1000000, method: '카드', memo: '현대카드' },
      interim: { amount: 0, method: null, memo: '' },
      balance: { amount: 3500000, method: '현금', memo: '인출' },
      usedAmount: 4200000,
    },
    consultNoteIds: ['consult-2'],
  },
  {
    id: 'prep-3',
    title: '예물 브랜드 리서치',
    category: '예물예단',
    assigneeName: '경영',
    checklist: { done: false, dueDate: '2026-08-18' },
    budget: {
      plannedAmount: 6000000,
      deposit: { amount: 0, method: null, memo: '' },
      interim: { amount: 0, method: null, memo: '' },
      balance: { amount: 6000000, method: '카드', memo: '롯데카드' },
      usedAmount: 5800000,
    },
    consultNoteIds: ['consult-1', 'consult-2'],
  },
  {
    id: 'prep-4',
    title: '청첩장 시안 3개 선정',
    category: '청첩장',
    assigneeName: null,
    checklist: { done: false, dueDate: '2026-09-01' },
    schedule: { scheduledAt: '2026-09-06T00:00:00+09:00', location: '이태원 브런치집', eventType: '청첩장모임' },
    budget: {
      plannedAmount: 800000,
      deposit: { amount: 0, method: null, memo: '' },
      interim: { amount: 0, method: null, memo: '' },
      balance: { amount: 800000, method: '카드', memo: '현대카드' },
      usedAmount: 620000,
    },
    consultNoteIds: [],
  },
  {
    id: 'prep-5',
    title: '혼수 리스트 초안',
    category: '혼수',
    assigneeName: '지영',
    checklist: { done: false, dueDate: '2026-09-10' },
    budget: {
      plannedAmount: 12000000,
      deposit: { amount: 0, method: null, memo: '' },
      interim: { amount: 0, method: null, memo: '' },
      balance: { amount: 12000000, method: '현금', memo: '계좌이체' },
      usedAmount: 8900000,
    },
    consultNoteIds: [],
  },
  {
    id: 'prep-6',
    title: '신혼여행 항공권 예약',
    category: '신혼여행',
    assigneeName: '경영',
    checklist: { done: false, dueDate: '2026-09-20' },
    budget: {
      plannedAmount: 9000000,
      deposit: { amount: 1500000, method: '카드', memo: '현대카드' },
      interim: { amount: 0, method: null, memo: '' },
      balance: { amount: 7500000, method: '현금', memo: '계좌이체' },
      usedAmount: 3200000,
    },
    consultNoteIds: [],
  },
  {
    id: 'prep-7',
    title: '본식 DVD 업체 미팅',
    category: '스드메',
    assigneeName: null,
    checklist: { done: false, dueDate: '2026-09-25' },
    schedule: { scheduledAt: '2026-08-20T15:00:00+09:00', location: '성수 플래너 오피스', eventType: '상담' },
    consultNoteIds: ['consult-3'],
  },
  {
    id: 'prep-8',
    title: '본식',
    category: '기타',
    assigneeName: null,
    schedule: { scheduledAt: `${weddingDate}T13:00:00+09:00`, location: '그랜드 볼룸', eventType: '본식' },
    consultNoteIds: [],
  },
];

export const mockConsultNotes: ConsultNote[] = [
  {
    id: 'consult-1',
    vendorName: 'W 웨딩홀',
    vendorType: '웨딩홀',
    contactPhone: '02-1234-5678',
    visitDate: '2026-08-05',
    status: 'done',
    keyMemos: ['보증인원 200명', '식사 6.8만원/인', '주말 오후 슬롯 가능'],
    questions: ['대관료 별도 여부', '폐백실 사용료', '주차 지원 규모'],
    address: '서울 강남구 논현동 200',
    lat: 37.5115,
    lng: 127.0298,
    photos: [
      { gradient: 'linear-gradient(135deg, #f6c98d, #f19a8e)' },
      { gradient: 'linear-gradient(135deg, #9fd4e0, #d7ecf0)' },
    ],
  },
  {
    id: 'consult-2',
    vendorName: '스튜디오 B',
    vendorType: '스드메',
    contactPhone: '010-2222-3333',
    visitDate: '2026-08-12',
    status: 'done',
    keyMemos: ['실내+야외 반반 컨셉', '원본 파일 제공'],
    questions: ['헤어·메이크업 제휴 리스트', '리터치 컷 수'],
    address: '서울 강남구 청담동 100',
    lat: 37.5253,
    lng: 127.0472,
    photos: [{ gradient: 'linear-gradient(135deg, #efe3d6, #d9cfc2)' }],
  },
  {
    id: 'consult-3',
    vendorName: '플래너 C',
    vendorType: '기타',
    contactPhone: '',
    visitDate: '2026-08-20',
    status: 'scheduled',
    address: '',
    lat: null,
    lng: null,
    keyMemos: [],
    questions: ['픽업 스드메 리스트', '폐백·이바지 대행 가능?'],
    photos: [],
  },
];

export const mockHoneymoon: Honeymoon = {
  destination: '몰디브',
  startDate: '2027-04-14',
  endDate: '2027-04-18',
  days: [
    {
      id: 'honeymoon-day-1',
      dayNumber: 1,
      title: '인천 → 몰디브 도착',
      detail: '말레 · 말레 공항 픽업 → 수상비행기',
      photos: [],
      budget: { plannedAmount: 0, usedAmount: 0, method: null, memo: '' },
    },
    {
      id: 'honeymoon-day-2',
      dayNumber: 2,
      title: '리조트 데이',
      detail: '바투 아일랜드 · 스노클링 + 인피니티 풀',
      photos: [],
      budget: { plannedAmount: 0, usedAmount: 0, method: null, memo: '' },
    },
    {
      id: 'honeymoon-day-3',
      dayNumber: 3,
      title: '돌핀 크루즈',
      detail: '남 말레 아톨 · 일몰 크루즈 예약',
      photos: [],
      budget: { plannedAmount: 0, usedAmount: 0, method: null, memo: '' },
    },
    {
      id: 'honeymoon-day-4',
      dayNumber: 4,
      title: '스파 & 저녁',
      detail: '리조트 내 · 커플 스파 + 프라이빗 디너',
      photos: [],
      budget: { plannedAmount: 0, usedAmount: 0, method: null, memo: '' },
    },
    {
      id: 'honeymoon-day-5',
      dayNumber: 5,
      title: '귀국',
      detail: '말레 → 인천 · 체크아웃 12:00',
      photos: [],
      budget: { plannedAmount: 0, usedAmount: 0, method: null, memo: '' },
    },
  ],
};
